Setup Popup Window for Work Section
chelobotix/Portafolio-Website pull request #15
Opened 2023-01-05 22:14 UTC by chelobotix

In this PR, I fulfilled the following tasks:
- [x] Create a Popup window for mobile and desktop versions.
- [x] Add a JavaScript array to store all the information for the projects.
- [x] Update the main page so that the projects section is created dynamically from a JS script
- [ x] Update the README file with the new feature

2023-01-05 23:06 UTC, huseyinbiyik requested changes
Hi @chelobotix and @adelphinsucasa,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![Almost there](https://media.giphy.com/media/Rv6GGaNrRbtNConlYo/giphy.gif)

## Highlights
- Works section created dynamically with JavaScript 👌

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
- [OPTIONAL] Please fix the license link on the Readme file. 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-05 23:06 UTC, huseyinbiyik commented on index.html
> +    <section class="section_works" id="Portoflio"></section>
Kindly fix the width of the modal as per the given Figma template.
Your design:

<img width="1316" alt="Screenshot 2023-01-06 at 1 29 48 AM" src="https://user-images.githubusercontent.com/25887253/210894606-b3d329b3-28e0-4428-8b78-10733ddd7842.png">

Figma template:
<img width="977" alt="Screenshot 2023-01-06 at 1 30 18 AM" src="https://user-images.githubusercontent.com/25887253/210894616-afd438fc-582f-48cd-bc3b-5e94f908dcce.png">

2023-01-05 23:06 UTC, huseyinbiyik commented on popup.js
> +  if (window.matchMedia('(max-width: 767px)').matches) {
Please fix the height of the modal on the mobile version. It uses almost the half of the page as seen below.

Figma template:
<img width="405" alt="Screenshot 2023-01-06 at 1 37 42 AM" src="https://user-images.githubusercontent.com/25887253/210895171-1b17b3df-fc98-4c56-83e2-7f5359a8f21a.png">
<img width="221" alt="Screenshot 2023-01-06 at 1 38 19 AM" src="https://user-images.githubusercontent.com/25887253/210895177-a3881872-b499-4555-b5b9-40fe9497491e.png">

2023-01-05 23:06 UTC, huseyinbiyik commented on index.html
> +            <button class="modal-btn2 btn_effects">See Source<i class="bi bi-github"></i></button>
Please fix the icon like on the Figma template. The icons is not under the link, it is just located on the next to it.
<img width="331" alt="Screenshot 2023-01-06 at 1 33 15 AM" src="https://user-images.githubusercontent.com/25887253/210895976-7bbdbb13-b4b6-4f94-8771-08707ed61c75.png">
<img width="331" alt="Screenshot 2023-01-06 at 1 33 26 AM" src="https://user-images.githubusercontent.com/25887253/210895977-66115b83-a3cf-4de0-b7d2-c9b2c8f1a595.png">

2023-01-05 23:06 UTC, huseyinbiyik commented on index.html
> +    <section class="section_works" id="Portoflio"></section>
Please make sure the Lorem Ipsum text is not overflowing from the modal and there is padding on the bottom of the text.
<img width="822" alt="Screenshot 2023-01-06 at 1 30 55 AM" src="https://user-images.githubusercontent.com/25887253/210896509-48721965-19b3-4515-ba5e-11d8e0909017.png">
Figma template:
<img width="423" alt="Screenshot 2023-01-06 at 1 31 17 AM" src="https://user-images.githubusercontent.com/25887253/210896517-6ab77e5f-358a-4bfe-9a8a-e26abff1aa9c.png">

2023-01-06 14:02 UTC, chelobotix commented
Observation 1: Kindly fix the width of the modal as per the given Figma template.

![image](https://user-images.githubusercontent.com/65084923/211018551-cc775d10-bbc1-48ba-8d1b-56ad7c9055cd.png)

Observation 2: Please fix the height of the modal on the mobile version. It uses almost half of the page as seen below.

![image](https://user-images.githubusercontent.com/65084923/211025368-46857cb3-b4f6-4714-b02b-04abc4615813.png)

![image](https://user-images.githubusercontent.com/65084923/211024171-f201ef1f-2a62-4087-a9da-e26f1dad49f4.png)

Observation 3: Please fix the icon like on the Figma template. The icons is not under the link, it is just located on the next to it.

![image](https://user-images.githubusercontent.com/65084923/211024396-043fe413-40d3-4bb1-926f-2d52e598899a.png)

Observation 4: Please make sure the Lorem Ipsum text is not overflowing from the modal and there is padding on the bottom of the text.

![image](https://user-images.githubusercontent.com/65084923/211026203-df2df109-8756-453f-8060-475e9f577ece.png)

2023-01-06 14:36 UTC, BregornOriginal approved these changes
## Hi @chelobotix 

## Your project is complete!  There is nothing else to say other than... it's time to merge it 

## Congratulations!

![tenor-1](https://user-images.githubusercontent.com/93630700/211033314-8d22340a-d47f-4af6-94a0-e40eac035e49.gif)

## Highlights

✅ Good commit history
✅ Good work implementing the changes from the previous reviewer

## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.
Cheers and Happy coding!:aplauso::aplauso::aplauso:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, remember to tag me in your question so I can receive the notification.
------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)[.](https://airtable.com/shrQAqnBwek5a0O0s)._)

2023-01-06 14:51 UTC, merged